### ISSUE TITLE
Reduce `YetStep` by adding more parsing rules.

### ISSUE THREAD

**Issue by h2oche** [es-meta/esmeta#28]
## TODO
- [x] `is (not) present` condition (a5218a8b80f2d08f38acc7ad9f6aecc36335d839)
- [x] give more specific types to `PerformStep` and `ReturnIfAbruptExpression`(fd785a77b40ad16b13e7cbc7d6ee794222de188d)
    - PerformStep.expr: InvokeExpression | ReturnIfAbruptExpression ...
- [x] abstract closure expression (10811567c6b2508a0ae8d976cb2c1a336d6f1eb5)
- [x] conditions using either/neither/both (64d3a5083f0a16672d6a17f23efcb3479205453c)
- [x] `the <component> of <base>` reference
- [x] active function object (ec83eba4f9b0cb5709a4f0ea26dc4bbdc4361566)
- [x] does not contain (00012377c19305a52b37d13ad18c0a16e3b6249b)
- [x] `the number of elements in <list>` (f35c2bc22407679141b38da79e757b1f3d4fbee3)
- [x] `the number of code units <string>` == `the length of <string>` (f35c2bc22407679141b38da79e757b1f3d4fbee3)
    - TODO: `the number of code points`, `the number of non-optional parameters`, ...
- [x] implication condition (ex: `If _fromIndex_ is *undefined*, then _n_ is 0.`) (022a881617dd5b49ca8528c21a4be258e19f7359)
- [x] a/an (ex: If |PrimaryExpression| is either an |ObjectLiteral| or an |ArrayLiteral|)
- [x] `<emu-grammar>` tag (ex: `If |Declaration| is <emu-grammar>Declaration : HoistableDeclaration</emu-grammar> , then [...]`)
- [x] this |NT| reference (ex: Let thisCall be this |CallExpression|.), |NT?| reference (ex: |Initializer?|)
- [x] covered by expression (191969a7d8efb8342823e7e3e58afa7fb3c1dd0a)
- [x] irregular `<emu-meta effects ...` -> just ignore?
- [x] finite condition
- [x] empty condition

## Result
191969a7d8efb8342823e7e3e58afa7fb3c1dd0a

```
* grammar:
  - productions: 356
    - lexical: 145
    - numeric string: 16
    - syntactic: 195
  - extended productions for web: 28
* algorithms: 2609 (76.12%)
  - complete: 1986
  - incomplete: 623
* algorithm steps: 18447 (91.63%)
  - complete: 16903
  - incompleted: 1544
```

**Comment by h2oche** [comment]
ad428c40b0c975dc77217d578cb8cefa349caa89
```
* grammar:
  - productions: 356
    - lexical: 145
    - numeric string: 16
    - syntactic: 195
  - extended productions for web: 28
* algorithms: 2609 (66.58%)
  - complete: 1737
  - incomplete: 872
* algorithm steps: 15378 (85.43%)
  - complete: 13138
  - incompleted: 2240
```

**Comment by h2oche** [comment]
a5218a8b80f2d08f38acc7ad9f6aecc36335d839

```
* grammar:
  - productions: 356
    - lexical: 145
    - numeric string: 16
    - syntactic: 195
  - extended productions for web: 28
* algorithms: 2609 (72.25%)
  - complete: 1885
  - incomplete: 724
* algorithm steps: 15658 (87.76%)
  - complete: 13742
  - incompleted: 1916
```
